### ISSUE TITLE
Could not find a version that satisfies the requirement sendria (from versions: none)

### ISSUE THREAD

**Issue by greenseeker** [msztolcman/sendria#11]
I'm not sure how to troubleshoot this. I can install sendria without issue on Ubuntu 21.10, but on Rocky 8 I get the following when using pip or pipx:
```
# pipx install sendria
Fatal error from pip prevented installation. Full pip output in file:
    /root/.local/pipx/logs/cmd_2022-01-04_01.31.17_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement sendria (from versions: none)
    ERROR: No matching distribution found for sendria

# pip install sendria
ERROR: Could not find a version that satisfies the requirement sendria (from versions: none)
ERROR: No matching distribution found for sendria

# python3 -m pip install sendria
ERROR: Could not find a version that satisfies the requirement sendria (from versions: none)
ERROR: No matching distribution found for sendria
```

I've done the usual steps of updating pip, pipx, setuptools, but no luck and I haven't been able to get any more helpful error messages.

**Comment by msztolcman** [comment]
Hello @greenseeker,

There is no obvious reason why Sendria couldn't be install on Rocky Linux. I never used it, but if this is standard Linux distribution, everything should work fine then. Do you have any issues with installing other packages? Or it's just Sendria?

Few questions about this kind of issues I found on:
https://bhch.github.io/posts/2017/04/fix-the-pip-error-couldnt-find-a-version-that-satisfies-the-requirement/
Could you please follow them?

If this did not help, please try to install Sendria using command:
`python3 -m pip install sendria -vvv`

and attach the output to this issue, then will try to find the reason.

**Comment by greenseeker** [comment]
Hi @msztolcman,

Rocky Linux is a RHEL clone to replace CentOS. I have not seen any issues installing other packages.

The only thing I hadn't already confirmed from that page is the Python version. 

I did notice on PyPI that you only support 3.7 and up. RHEL 8 standardizes on 3.6, but after adding 3.9 and installing like so...
```
# PIPX_DEFAULT_PYTHON=/usr/bin/python3.9 pipx install sendria
  installed package sendria 2.2.2, installed using Python 3.9.6
  These apps are now globally available
    - sendria
done! ✨ 🌟 ✨
```
...you can see it was successful.

**Comment by msztolcman** [comment]
@greenseeker,

Super! Glad it works now. 

And thanks for explanations about Rocky Linux, I never realized this distro - I'm from Debian world ;)
