### ISSUE TITLE
Typo in mailtrap blog post

### ISSUE THREAD

**Issue by 0xAliRaza** [msztolcman/sendria#13]
Missing semicolon.
![image](https://user-images.githubusercontent.com/33368198/152676815-9a1efb17-796b-4918-b16c-e5608d0d3515.png)

https://mailtrap.io/blog/phpmailer/#:~:text=generated%20by%20Mailtrap-,%24mail%2D%3EPassword%20%3D%20%271a2b3c4d5e6f7g%E2%80%99,-//paste%20one%20generated

**Comment by msztolcman** [comment]
Hello @0xAliRaza,

Thank you for your report, however this is not mailtrap.io :) Mailtrap.io has in common with Sendria just one thing: Sendria's precedessor name was `Mailtrap`, but I've changed this some time ago to `Sendria` :) Please report this issue to mailtrap.io.
