### ISSUE TITLE
Language processing issue

### ISSUE THREAD

**Issue by KathrynN** [msztolcman/sendria#2]
Hi!

I loved mailtrap and use it for testing e.g. registration emails.  
Since the latest vs of mailtrap breaks the functionality for new users, I'm trying to migrate over to sendria.
However, emails sent in other languages are now broken, where previously they worked.
For example, I expected the string "lösenord" (Swedish for password) but using the new REST API, I now get "lÃ¶senord".

Thanks!

**Comment by msztolcman** [comment]
Hi @KathrynN,

Great to hear you love Sendria! Thank for your feedback 👍 

I've tested locally sending some content with characters outside ASCII, also copied some swedish texts from some websites, and send it to Sendria. Unfortunatelly I can't reproduce this problem.

Could you please show me some content of incorrectly displayed message with all headers? Content of 'Source' tab would be great, then I'll be able to reproduce and fix this issue. Thanks!

**Comment by KathrynN** [comment]
Seems to be working!  Must have been a temporary glitch, my apologies :) 
Keep up the awesome work, this project makes it so much easier to write automatic integration tests, and saved me hours and hours of bug fixes.
Best,
Kat
